USE library_db;

CREATE OR REPLACE VIEW V_RENTAL_STATUS AS
SELECT
    R.RENTAL_ID,
    R.MEMBER_ID,
    R.BOOK_ID,
    R.RENTAL_DATE,
    R.DUE_DATE,
    R.RETURN_DATE,
    R.RENTAL_STATUS,
    CASE
        WHEN R.RENTAL_STATUS = '대여중'
             AND R.RETURN_DATE IS NULL
             AND R.DUE_DATE < CURDATE()
        THEN '연체중'
        ELSE R.RENTAL_STATUS
    END AS DISPLAY_STATUS
FROM EX_RENTAL R;